services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/redislogin-webapp:latest
    ports:
      - "5461:80"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
    networks:
      - redis-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis_data: