name: Deploy Redis Login

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: ./RedisLogin/RedisLogin
      run: dotnet restore

    - name: Build
      working-directory: ./RedisLogin/RedisLogin
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./RedisLogin/RedisLogin
      run: dotnet test --no-build --verbosity normal

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker images
      working-directory: ./RedisLogin/RedisLogin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
